// Valores predeterminados para cada nivel de cuenta
export const DEFAULT_ACCOUNT_VALUES = {
    1: { number: '41352805', description: 'Cuenta Ingresos Gravados al 19% (CR)', modules: 'Facturas de venta, POS', type: 'CR' },
    2: { number: '41352815', description: 'Cuenta Ingresos Gravados al 5% (CR)', modules: 'Facturas de venta, POS', type: 'CR' },
    3: { number: '41352810', description: 'Cuenta Ingresos No Gravados (CR)', modules: 'Facturas de venta, POS', type: 'CR' },
    4: { number: '613528', description: 'Cuenta costos de venta (DB)', modules: 'Facturas de venta, POS', type: 'DB' },
    5: { number: '14350105', description: 'Mercancias no fabricadas vendidas - en operaciones gravadas. (CR)', modules: 'Facturas de venta, POS, Remisión', type: 'CR' },
    6: { number: '14350110', description: 'Mercancias no fabricadas vendidas- en operaciones no gravadas. (CR)', modules: 'Facturas de venta, POS, Remisión', type: 'CR' },
    7: { number: '14300105', description: 'Mercancias fabricadas vendidas - en operaciones gravadas. (CR)', modules: 'Facturas de venta, POS, Remisión', type: 'CR' },
    8: { number: '14300110', description: 'Mercancias fabricadas vendidas - en operaciones no gravadas. (CR)', modules: 'Facturas de venta, POS, Remisión', type: 'CR' },
    9: { number: '143005', description: 'Mercancias fabricadas - transformadas desde materia prima. (DB)', modules: 'Transformación de inventarios', type: 'DB' },
    10: { number: '146510', description: 'Mercancias en traslado entre bodegas - salida. (DB)', modules: 'Traslados de inventarios', type: 'DB' },
    11: { number: '14350205', description: 'Mercancias no fabricadas compradas - en operaciones gravadas. (DB)', modules: 'Factura de proveedor', type: 'DB' },
    12: { number: '14350210', description: 'Mercancias no fabricadas compradas- en operaciones no gravadas. (DB)', modules: 'Factura de proveedor', type: 'DB' },
    13: { number: '14350215', description: 'Mercancias no fabricadas compradas- en importaciones. (DB)', modules: 'Liquidación Importaciones', type: 'DB' },
    14: { number: '140502', description: 'Materia prima transformada a Mercancias fabricadas. (CR)', modules: 'Transformación de inventarios', type: 'CR' },
    15: { number: '140501', description: 'Materias primas compradas. (DB)', modules: 'Factura de proveedor', type: 'DB' },
    16: { number: '147001', description: 'Mercancias remisionadas - salida. (CR)', modules: 'Remisiones', type: 'CR' },
    17: { number: '147002', description: 'Mercancias remisionadas - convertido a factura. (DB)', modules: 'Remisiones', type: 'DB' },
    18: { number: '14650505', description: 'Inventario en transito de importación (DB/CR)', modules: 'Importaciones', type: 'DB/CR' },
    19: { number: '14650506', description: 'Ajsutes de inventarios', modules: 'Ajuste de inventarios', type: 'DB/CR' },
    20: { number: '14650507', description: 'Debito en factura cerrada sin pago', modules: 'Facturación', type: 'DB' },
    21: { number: '14650508', description: 'Credito en descuento sobre factura de proveedor', modules: 'Facturas Proveedor', type: 'CR' },
    22: { number: '14650509', description: 'Cuenta por cobrar en remisiones (cartera) (DB)', modules: 'Remisiones', type: 'DB' },
    23: { number: '14650510', description: 'Inventarios en remisiones (CR)', modules: 'Remisiones', type: 'CR' },
    24: { number: '14650511', description: 'Ingreso en remisiones (CR)', modules: 'Remisiones', type: 'CR' },
    25: { number: '14650512', description: 'Descuento Financiero en factura de venta (DB)', modules: 'Facturación', type: 'DB' },
    26: { number: '14650513', description: 'IVA en devoluciones al 5% (DB)', modules: 'Facturación', type: 'DB' },
    27: { number: '14650514', description: 'IVA en devoluciones al 19% (DB)', modules: 'Facturación', type: 'DB' },
};

